[2025-04-02T11:35:16.815+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-02T11:35:16.823+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_yf_scraper.run_reddit manual__2025-04-02T03:31:50.764765+00:00 [queued]>
[2025-04-02T11:35:16.826+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_yf_scraper.run_reddit manual__2025-04-02T03:31:50.764765+00:00 [queued]>
[2025-04-02T11:35:16.827+0800] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-02T11:35:16.832+0800] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): run_reddit> on 2025-04-02 03:31:50.764765+00:00
[2025-04-02T11:35:16.835+0800] {standard_task_runner.py:72} INFO - Started process 20531 to run task
[2025-04-02T11:35:16.838+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_yf_scraper', 'run_reddit', 'manual__2025-04-02T03:31:50.764765+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/var/folders/xg/h9xj0trn3dxds251bj2q6hf80000gn/T/tmpwcs78ltq']
[2025-04-02T11:35:16.839+0800] {standard_task_runner.py:105} INFO - Job 170: Subtask run_reddit
[2025-04-02T11:35:16.876+0800] {task_command.py:467} INFO - Running <TaskInstance: reddit_yf_scraper.run_reddit manual__2025-04-02T03:31:50.764765+00:00 [running]> on host ervins-macbook-air-2.local
[2025-04-02T11:35:16.914+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='reddit_yf_scraper' AIRFLOW_CTX_TASK_ID='run_reddit' AIRFLOW_CTX_EXECUTION_DATE='2025-04-02T03:31:50.764765+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-02T03:31:50.764765+00:00'
[2025-04-02T11:35:16.915+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-02T11:35:16.915+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-02T11:35:16.915+0800] {logging_mixin.py:190} INFO - Current task name:run_reddit state:running start_date:2025-04-02 03:35:16.823616+00:00
[2025-04-02T11:35:16.915+0800] {logging_mixin.py:190} INFO - Dag name:reddit_yf_scraper and current dag run status:running
[2025-04-02T11:35:16.916+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-02T11:35:17.706+0800] {patcher.py:346} INFO - patching driver executable /Users/ervinyeoh/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2025-04-02T11:35:21.292+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/dag.py", line 54, in run_reddit
    run_reddit_scraper(tickers)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/reddit_scraper.py", line 22, in run_reddit_scraper
    driver = uc.Chrome()
             ^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:59669
from session not created: This version of ChromeDriver only supports Chrome version 135
Current browser version is 134.0.6998.166
Stacktrace:
0   undetected_chromedriver             0x0000000102c58168 undetected_chromedriver + 6177128
1   undetected_chromedriver             0x0000000102c4f82a undetected_chromedriver + 6141994
2   undetected_chromedriver             0x00000001026d9e00 undetected_chromedriver + 417280
3   undetected_chromedriver             0x000000010271a8a6 undetected_chromedriver + 682150
4   undetected_chromedriver             0x0000000102719814 undetected_chromedriver + 677908
5   undetected_chromedriver             0x000000010270efae undetected_chromedriver + 634798
6   undetected_chromedriver             0x000000010275ff22 undetected_chromedriver + 966434
7   undetected_chromedriver             0x000000010275f416 undetected_chromedriver + 963606
8   undetected_chromedriver             0x00000001027514c3 undetected_chromedriver + 906435
9   undetected_chromedriver             0x000000010271d885 undetected_chromedriver + 694405
10  undetected_chromedriver             0x000000010271e4f1 undetected_chromedriver + 697585
11  undetected_chromedriver             0x0000000102c14950 undetected_chromedriver + 5900624
12  undetected_chromedriver             0x0000000102c189e1 undetected_chromedriver + 5917153
13  undetected_chromedriver             0x0000000102beee14 undetected_chromedriver + 5746196
14  undetected_chromedriver             0x0000000102c1940b undetected_chromedriver + 5919755
15  undetected_chromedriver             0x0000000102bdd574 undetected_chromedriver + 5674356
16  undetected_chromedriver             0x0000000102c3ce88 undetected_chromedriver + 6065800
17  undetected_chromedriver             0x0000000102c3d050 undetected_chromedriver + 6066256
18  undetected_chromedriver             0x0000000102c4f3f1 undetected_chromedriver + 6140913
19  libsystem_pthread.dylib             0x00007ff8090b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8090acc7b thread_start + 15

[2025-04-02T11:35:21.323+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-02T11:35:21.324+0800] {logging_mixin.py:190} INFO - Task start:2025-04-02 03:35:16.823616+00:00 end:2025-04-02 03:35:21.322156+00:00 duration:4.49854
[2025-04-02T11:35:21.324+0800] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): run_reddit> dag:<DAG: reddit_yf_scraper> dagrun:<DagRun reddit_yf_scraper @ 2025-04-02 03:31:50.764765+00:00: manual__2025-04-02T03:31:50.764765+00:00, state:running, queued_at: 2025-04-02 03:31:50.777486+00:00. externally triggered: True>
[2025-04-02T11:35:21.324+0800] {logging_mixin.py:190} INFO - Failure caused by Message: session not created: cannot connect to chrome at 127.0.0.1:59669
from session not created: This version of ChromeDriver only supports Chrome version 135
Current browser version is 134.0.6998.166
Stacktrace:
0   undetected_chromedriver             0x0000000102c58168 undetected_chromedriver + 6177128
1   undetected_chromedriver             0x0000000102c4f82a undetected_chromedriver + 6141994
2   undetected_chromedriver             0x00000001026d9e00 undetected_chromedriver + 417280
3   undetected_chromedriver             0x000000010271a8a6 undetected_chromedriver + 682150
4   undetected_chromedriver             0x0000000102719814 undetected_chromedriver + 677908
5   undetected_chromedriver             0x000000010270efae undetected_chromedriver + 634798
6   undetected_chromedriver             0x000000010275ff22 undetected_chromedriver + 966434
7   undetected_chromedriver             0x000000010275f416 undetected_chromedriver + 963606
8   undetected_chromedriver             0x00000001027514c3 undetected_chromedriver + 906435
9   undetected_chromedriver             0x000000010271d885 undetected_chromedriver + 694405
10  undetected_chromedriver             0x000000010271e4f1 undetected_chromedriver + 697585
11  undetected_chromedriver             0x0000000102c14950 undetected_chromedriver + 5900624
12  undetected_chromedriver             0x0000000102c189e1 undetected_chromedriver + 5917153
13  undetected_chromedriver             0x0000000102beee14 undetected_chromedriver + 5746196
14  undetected_chromedriver             0x0000000102c1940b undetected_chromedriver + 5919755
15  undetected_chromedriver             0x0000000102bdd574 undetected_chromedriver + 5674356
16  undetected_chromedriver             0x0000000102c3ce88 undetected_chromedriver + 6065800
17  undetected_chromedriver             0x0000000102c3d050 undetected_chromedriver + 6066256
18  undetected_chromedriver             0x0000000102c4f3f1 undetected_chromedriver + 6140913
19  libsystem_pthread.dylib             0x00007ff8090b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8090acc7b thread_start + 15
[2025-04-02T11:35:21.325+0800] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=reddit_yf_scraper, task_id=run_reddit, run_id=manual__2025-04-02T03:31:50.764765+00:00, execution_date=20250402T033150, start_date=20250402T033516, end_date=20250402T033521
[2025-04-02T11:35:21.348+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-02T11:35:21.351+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 170 for task run_reddit (Message: session not created: cannot connect to chrome at 127.0.0.1:59669
from session not created: This version of ChromeDriver only supports Chrome version 135
Current browser version is 134.0.6998.166
Stacktrace:
0   undetected_chromedriver             0x0000000102c58168 undetected_chromedriver + 6177128
1   undetected_chromedriver             0x0000000102c4f82a undetected_chromedriver + 6141994
2   undetected_chromedriver             0x00000001026d9e00 undetected_chromedriver + 417280
3   undetected_chromedriver             0x000000010271a8a6 undetected_chromedriver + 682150
4   undetected_chromedriver             0x0000000102719814 undetected_chromedriver + 677908
5   undetected_chromedriver             0x000000010270efae undetected_chromedriver + 634798
6   undetected_chromedriver             0x000000010275ff22 undetected_chromedriver + 966434
7   undetected_chromedriver             0x000000010275f416 undetected_chromedriver + 963606
8   undetected_chromedriver             0x00000001027514c3 undetected_chromedriver + 906435
9   undetected_chromedriver             0x000000010271d885 undetected_chromedriver + 694405
10  undetected_chromedriver             0x000000010271e4f1 undetected_chromedriver + 697585
11  undetected_chromedriver             0x0000000102c14950 undetected_chromedriver + 5900624
12  undetected_chromedriver             0x0000000102c189e1 undetected_chromedriver + 5917153
13  undetected_chromedriver             0x0000000102beee14 undetected_chromedriver + 5746196
14  undetected_chromedriver             0x0000000102c1940b undetected_chromedriver + 5919755
15  undetected_chromedriver             0x0000000102bdd574 undetected_chromedriver + 5674356
16  undetected_chromedriver             0x0000000102c3ce88 undetected_chromedriver + 6065800
17  undetected_chromedriver             0x0000000102c3d050 undetected_chromedriver + 6066256
18  undetected_chromedriver             0x0000000102c4f3f1 undetected_chromedriver + 6140913
19  libsystem_pthread.dylib             0x00007ff8090b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8090acc7b thread_start + 15
; 20531)
Traceback (most recent call last):
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/dag.py", line 54, in run_reddit
    run_reddit_scraper(tickers)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/reddit_scraper.py", line 22, in run_reddit_scraper
    driver = uc.Chrome()
             ^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:59669
from session not created: This version of ChromeDriver only supports Chrome version 135
Current browser version is 134.0.6998.166
Stacktrace:
0   undetected_chromedriver             0x0000000102c58168 undetected_chromedriver + 6177128
1   undetected_chromedriver             0x0000000102c4f82a undetected_chromedriver + 6141994
2   undetected_chromedriver             0x00000001026d9e00 undetected_chromedriver + 417280
3   undetected_chromedriver             0x000000010271a8a6 undetected_chromedriver + 682150
4   undetected_chromedriver             0x0000000102719814 undetected_chromedriver + 677908
5   undetected_chromedriver             0x000000010270efae undetected_chromedriver + 634798
6   undetected_chromedriver             0x000000010275ff22 undetected_chromedriver + 966434
7   undetected_chromedriver             0x000000010275f416 undetected_chromedriver + 963606
8   undetected_chromedriver             0x00000001027514c3 undetected_chromedriver + 906435
9   undetected_chromedriver             0x000000010271d885 undetected_chromedriver + 694405
10  undetected_chromedriver             0x000000010271e4f1 undetected_chromedriver + 697585
11  undetected_chromedriver             0x0000000102c14950 undetected_chromedriver + 5900624
12  undetected_chromedriver             0x0000000102c189e1 undetected_chromedriver + 5917153
13  undetected_chromedriver             0x0000000102beee14 undetected_chromedriver + 5746196
14  undetected_chromedriver             0x0000000102c1940b undetected_chromedriver + 5919755
15  undetected_chromedriver             0x0000000102bdd574 undetected_chromedriver + 5674356
16  undetected_chromedriver             0x0000000102c3ce88 undetected_chromedriver + 6065800
17  undetected_chromedriver             0x0000000102c3d050 undetected_chromedriver + 6066256
18  undetected_chromedriver             0x0000000102c4f3f1 undetected_chromedriver + 6140913
19  libsystem_pthread.dylib             0x00007ff8090b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8090acc7b thread_start + 15

[2025-04-02T11:35:21.398+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-02T11:35:21.447+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-02T11:35:21.448+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
