[2025-04-02T11:31:19.840+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-02T11:31:19.848+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_yf_scraper.run_reddit scheduled__2025-03-31T16:00:00+00:00 [queued]>
[2025-04-02T11:31:19.852+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_yf_scraper.run_reddit scheduled__2025-03-31T16:00:00+00:00 [queued]>
[2025-04-02T11:31:19.852+0800] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-02T11:31:19.858+0800] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): run_reddit> on 2025-03-31 16:00:00+00:00
[2025-04-02T11:31:19.860+0800] {standard_task_runner.py:72} INFO - Started process 20348 to run task
[2025-04-02T11:31:19.863+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_yf_scraper', 'run_reddit', 'scheduled__2025-03-31T16:00:00+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/var/folders/xg/h9xj0trn3dxds251bj2q6hf80000gn/T/tmp_105_ej5']
[2025-04-02T11:31:19.864+0800] {standard_task_runner.py:105} INFO - Job 167: Subtask run_reddit
[2025-04-02T11:31:19.898+0800] {task_command.py:467} INFO - Running <TaskInstance: reddit_yf_scraper.run_reddit scheduled__2025-03-31T16:00:00+00:00 [running]> on host ervins-macbook-air-2.local
[2025-04-02T11:31:19.930+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='reddit_yf_scraper' AIRFLOW_CTX_TASK_ID='run_reddit' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-31T16:00:00+00:00'
[2025-04-02T11:31:19.931+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-02T11:31:19.931+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-02T11:31:19.932+0800] {logging_mixin.py:190} INFO - Current task name:run_reddit state:running start_date:2025-04-02 03:31:19.848886+00:00
[2025-04-02T11:31:19.932+0800] {logging_mixin.py:190} INFO - Dag name:reddit_yf_scraper and current dag run status:running
[2025-04-02T11:31:19.932+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-02T11:31:20.673+0800] {patcher.py:346} INFO - patching driver executable /Users/ervinyeoh/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2025-04-02T11:31:24.212+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/dag.py", line 54, in run_reddit
    run_reddit_scraper(tickers)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/reddit_scraper.py", line 21, in run_reddit_scraper
    driver = uc.Chrome()
             ^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:59374
from session not created: This version of ChromeDriver only supports Chrome version 135
Current browser version is 134.0.6998.166
Stacktrace:
0   undetected_chromedriver             0x00000001007c8168 undetected_chromedriver + 6177128
1   undetected_chromedriver             0x00000001007bf82a undetected_chromedriver + 6141994
2   undetected_chromedriver             0x0000000100249e00 undetected_chromedriver + 417280
3   undetected_chromedriver             0x000000010028a8a6 undetected_chromedriver + 682150
4   undetected_chromedriver             0x0000000100289814 undetected_chromedriver + 677908
5   undetected_chromedriver             0x000000010027efae undetected_chromedriver + 634798
6   undetected_chromedriver             0x00000001002cff22 undetected_chromedriver + 966434
7   undetected_chromedriver             0x00000001002cf416 undetected_chromedriver + 963606
8   undetected_chromedriver             0x00000001002c14c3 undetected_chromedriver + 906435
9   undetected_chromedriver             0x000000010028d885 undetected_chromedriver + 694405
10  undetected_chromedriver             0x000000010028e4f1 undetected_chromedriver + 697585
11  undetected_chromedriver             0x0000000100784950 undetected_chromedriver + 5900624
12  undetected_chromedriver             0x00000001007889e1 undetected_chromedriver + 5917153
13  undetected_chromedriver             0x000000010075ee14 undetected_chromedriver + 5746196
14  undetected_chromedriver             0x000000010078940b undetected_chromedriver + 5919755
15  undetected_chromedriver             0x000000010074d574 undetected_chromedriver + 5674356
16  undetected_chromedriver             0x00000001007ace88 undetected_chromedriver + 6065800
17  undetected_chromedriver             0x00000001007ad050 undetected_chromedriver + 6066256
18  undetected_chromedriver             0x00000001007bf3f1 undetected_chromedriver + 6140913
19  libsystem_pthread.dylib             0x00007ff8090b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8090acc7b thread_start + 15

[2025-04-02T11:31:24.227+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-02T11:31:24.227+0800] {logging_mixin.py:190} INFO - Task start:2025-04-02 03:31:19.848886+00:00 end:2025-04-02 03:31:24.226168+00:00 duration:4.377282
[2025-04-02T11:31:24.227+0800] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): run_reddit> dag:<DAG: reddit_yf_scraper> dagrun:<DagRun reddit_yf_scraper @ 2025-03-31 16:00:00+00:00: scheduled__2025-03-31T16:00:00+00:00, state:running, queued_at: 2025-04-02 03:23:33.127142+00:00. externally triggered: False>
[2025-04-02T11:31:24.228+0800] {logging_mixin.py:190} INFO - Failure caused by Message: session not created: cannot connect to chrome at 127.0.0.1:59374
from session not created: This version of ChromeDriver only supports Chrome version 135
Current browser version is 134.0.6998.166
Stacktrace:
0   undetected_chromedriver             0x00000001007c8168 undetected_chromedriver + 6177128
1   undetected_chromedriver             0x00000001007bf82a undetected_chromedriver + 6141994
2   undetected_chromedriver             0x0000000100249e00 undetected_chromedriver + 417280
3   undetected_chromedriver             0x000000010028a8a6 undetected_chromedriver + 682150
4   undetected_chromedriver             0x0000000100289814 undetected_chromedriver + 677908
5   undetected_chromedriver             0x000000010027efae undetected_chromedriver + 634798
6   undetected_chromedriver             0x00000001002cff22 undetected_chromedriver + 966434
7   undetected_chromedriver             0x00000001002cf416 undetected_chromedriver + 963606
8   undetected_chromedriver             0x00000001002c14c3 undetected_chromedriver + 906435
9   undetected_chromedriver             0x000000010028d885 undetected_chromedriver + 694405
10  undetected_chromedriver             0x000000010028e4f1 undetected_chromedriver + 697585
11  undetected_chromedriver             0x0000000100784950 undetected_chromedriver + 5900624
12  undetected_chromedriver             0x00000001007889e1 undetected_chromedriver + 5917153
13  undetected_chromedriver             0x000000010075ee14 undetected_chromedriver + 5746196
14  undetected_chromedriver             0x000000010078940b undetected_chromedriver + 5919755
15  undetected_chromedriver             0x000000010074d574 undetected_chromedriver + 5674356
16  undetected_chromedriver             0x00000001007ace88 undetected_chromedriver + 6065800
17  undetected_chromedriver             0x00000001007ad050 undetected_chromedriver + 6066256
18  undetected_chromedriver             0x00000001007bf3f1 undetected_chromedriver + 6140913
19  libsystem_pthread.dylib             0x00007ff8090b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8090acc7b thread_start + 15
[2025-04-02T11:31:24.228+0800] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=reddit_yf_scraper, task_id=run_reddit, run_id=scheduled__2025-03-31T16:00:00+00:00, execution_date=20250331T160000, start_date=20250402T033119, end_date=20250402T033124
[2025-04-02T11:31:24.242+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-02T11:31:24.243+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 167 for task run_reddit (Message: session not created: cannot connect to chrome at 127.0.0.1:59374
from session not created: This version of ChromeDriver only supports Chrome version 135
Current browser version is 134.0.6998.166
Stacktrace:
0   undetected_chromedriver             0x00000001007c8168 undetected_chromedriver + 6177128
1   undetected_chromedriver             0x00000001007bf82a undetected_chromedriver + 6141994
2   undetected_chromedriver             0x0000000100249e00 undetected_chromedriver + 417280
3   undetected_chromedriver             0x000000010028a8a6 undetected_chromedriver + 682150
4   undetected_chromedriver             0x0000000100289814 undetected_chromedriver + 677908
5   undetected_chromedriver             0x000000010027efae undetected_chromedriver + 634798
6   undetected_chromedriver             0x00000001002cff22 undetected_chromedriver + 966434
7   undetected_chromedriver             0x00000001002cf416 undetected_chromedriver + 963606
8   undetected_chromedriver             0x00000001002c14c3 undetected_chromedriver + 906435
9   undetected_chromedriver             0x000000010028d885 undetected_chromedriver + 694405
10  undetected_chromedriver             0x000000010028e4f1 undetected_chromedriver + 697585
11  undetected_chromedriver             0x0000000100784950 undetected_chromedriver + 5900624
12  undetected_chromedriver             0x00000001007889e1 undetected_chromedriver + 5917153
13  undetected_chromedriver             0x000000010075ee14 undetected_chromedriver + 5746196
14  undetected_chromedriver             0x000000010078940b undetected_chromedriver + 5919755
15  undetected_chromedriver             0x000000010074d574 undetected_chromedriver + 5674356
16  undetected_chromedriver             0x00000001007ace88 undetected_chromedriver + 6065800
17  undetected_chromedriver             0x00000001007ad050 undetected_chromedriver + 6066256
18  undetected_chromedriver             0x00000001007bf3f1 undetected_chromedriver + 6140913
19  libsystem_pthread.dylib             0x00007ff8090b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8090acc7b thread_start + 15
; 20348)
Traceback (most recent call last):
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/dag.py", line 54, in run_reddit
    run_reddit_scraper(tickers)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/reddit_scraper.py", line 21, in run_reddit_scraper
    driver = uc.Chrome()
             ^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:59374
from session not created: This version of ChromeDriver only supports Chrome version 135
Current browser version is 134.0.6998.166
Stacktrace:
0   undetected_chromedriver             0x00000001007c8168 undetected_chromedriver + 6177128
1   undetected_chromedriver             0x00000001007bf82a undetected_chromedriver + 6141994
2   undetected_chromedriver             0x0000000100249e00 undetected_chromedriver + 417280
3   undetected_chromedriver             0x000000010028a8a6 undetected_chromedriver + 682150
4   undetected_chromedriver             0x0000000100289814 undetected_chromedriver + 677908
5   undetected_chromedriver             0x000000010027efae undetected_chromedriver + 634798
6   undetected_chromedriver             0x00000001002cff22 undetected_chromedriver + 966434
7   undetected_chromedriver             0x00000001002cf416 undetected_chromedriver + 963606
8   undetected_chromedriver             0x00000001002c14c3 undetected_chromedriver + 906435
9   undetected_chromedriver             0x000000010028d885 undetected_chromedriver + 694405
10  undetected_chromedriver             0x000000010028e4f1 undetected_chromedriver + 697585
11  undetected_chromedriver             0x0000000100784950 undetected_chromedriver + 5900624
12  undetected_chromedriver             0x00000001007889e1 undetected_chromedriver + 5917153
13  undetected_chromedriver             0x000000010075ee14 undetected_chromedriver + 5746196
14  undetected_chromedriver             0x000000010078940b undetected_chromedriver + 5919755
15  undetected_chromedriver             0x000000010074d574 undetected_chromedriver + 5674356
16  undetected_chromedriver             0x00000001007ace88 undetected_chromedriver + 6065800
17  undetected_chromedriver             0x00000001007ad050 undetected_chromedriver + 6066256
18  undetected_chromedriver             0x00000001007bf3f1 undetected_chromedriver + 6140913
19  libsystem_pthread.dylib             0x00007ff8090b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8090acc7b thread_start + 15

[2025-04-02T11:31:24.266+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-02T11:31:24.288+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-02T11:31:24.291+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
