[2025-04-18T22:04:22.958+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T22:04:22.963+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_yf_scraper.get_tickers manual__2025-04-18T14:04:18.822513+00:00 [queued]>
[2025-04-18T22:04:22.965+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_yf_scraper.get_tickers manual__2025-04-18T14:04:18.822513+00:00 [queued]>
[2025-04-18T22:04:22.965+0800] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-18T22:04:22.971+0800] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): get_tickers> on 2025-04-18 14:04:18.822513+00:00
[2025-04-18T22:04:22.975+0800] {standard_task_runner.py:72} INFO - Started process 96188 to run task
[2025-04-18T22:04:22.979+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_yf_scraper', 'get_tickers', 'manual__2025-04-18T14:04:18.822513+00:00', '--job-id', '511', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/var/folders/2f/rw5w89ss6nl38qvq2cxrh29w0000gn/T/tmpqzu7h9we']
[2025-04-18T22:04:22.980+0800] {standard_task_runner.py:105} INFO - Job 511: Subtask get_tickers
[2025-04-18T22:04:23.000+0800] {task_command.py:467} INFO - Running <TaskInstance: reddit_yf_scraper.get_tickers manual__2025-04-18T14:04:18.822513+00:00 [running]> on host yueyaos-macbook-pro.local
[2025-04-18T22:04:23.038+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='reddit_yf_scraper' AIRFLOW_CTX_TASK_ID='get_tickers' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T14:04:18.822513+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T14:04:18.822513+00:00'
[2025-04-18T22:04:23.039+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-18T22:04:23.039+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-18T22:04:23.039+0800] {logging_mixin.py:190} INFO - Current task name:get_tickers state:running start_date:2025-04-18 14:04:22.963310+00:00
[2025-04-18T22:04:23.040+0800] {logging_mixin.py:190} INFO - Dag name:reddit_yf_scraper and current dag run status:running
[2025-04-18T22:04:23.040+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T22:04:23.041+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/dags/load_tickers.py", line 14, in load_sp500_tickers
    sp500_df = pd.read_csv(SP500_CSV_PATH)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
NotADirectoryError: [Errno 20] Not a directory: '/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/is3107zyy-7bfd94aff019.json/sp500_companies.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/dags/dag.py", line 103, in get_tickers
    return load_sp500_tickers()
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/dags/load_tickers.py", line 19, in load_sp500_tickers
    raise Exception(f"❌ Error loading S&P 500 tickers: {e}")
Exception: ❌ Error loading S&P 500 tickers: [Errno 20] Not a directory: '/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/is3107zyy-7bfd94aff019.json/sp500_companies.csv'
[2025-04-18T22:04:23.047+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-18T22:04:23.048+0800] {logging_mixin.py:190} INFO - Task start:2025-04-18 14:04:22.963310+00:00 end:2025-04-18 14:04:23.047604+00:00 duration:0.084294
[2025-04-18T22:04:23.048+0800] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): get_tickers> dag:<DAG: reddit_yf_scraper> dagrun:<DagRun reddit_yf_scraper @ 2025-04-18 14:04:18.822513+00:00: manual__2025-04-18T14:04:18.822513+00:00, state:running, queued_at: 2025-04-18 14:04:18.831350+00:00. externally triggered: True>
[2025-04-18T22:04:23.048+0800] {logging_mixin.py:190} INFO - Failure caused by ❌ Error loading S&P 500 tickers: [Errno 20] Not a directory: '/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/is3107zyy-7bfd94aff019.json/sp500_companies.csv'
[2025-04-18T22:04:23.048+0800] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=reddit_yf_scraper, task_id=get_tickers, run_id=manual__2025-04-18T14:04:18.822513+00:00, execution_date=20250418T140418, start_date=20250418T140422, end_date=20250418T140423
[2025-04-18T22:04:23.057+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T22:04:23.057+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 511 for task get_tickers (❌ Error loading S&P 500 tickers: [Errno 20] Not a directory: '/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/is3107zyy-7bfd94aff019.json/sp500_companies.csv'; 96188)
Traceback (most recent call last):
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/dags/load_tickers.py", line 14, in load_sp500_tickers
    sp500_df = pd.read_csv(SP500_CSV_PATH)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
NotADirectoryError: [Errno 20] Not a directory: '/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/is3107zyy-7bfd94aff019.json/sp500_companies.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/dags/dag.py", line 103, in get_tickers
    return load_sp500_tickers()
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/dags/load_tickers.py", line 19, in load_sp500_tickers
    raise Exception(f"❌ Error loading S&P 500 tickers: {e}")
Exception: ❌ Error loading S&P 500 tickers: [Errno 20] Not a directory: '/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/is3107zyy-7bfd94aff019.json/sp500_companies.csv'
[2025-04-18T22:04:23.082+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-18T22:04:23.094+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T22:04:23.094+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
